### ISSUE TITLE
fix daily run

### ISSUE THREAD

**Issue by ruebenramirez** [Nebulaworks/nix-garage#43]
Our daily run is broken.  E.g. https://github.com/Nebulaworks/nix-garage/runs/4417861281?check_suite_focus=true#step:4:307

I believe this is because we're referencing `docker.io/nebulaworks/awsutils` (where the `latest` tag is implied). 

Taking a look at the [container image tags](https://hub.docker.com/r/nebulaworks/awsutils/tags) on the docker hub registry, I'm not seeing a `latest` tag available.

Potential solutions:
- produce a `latest` tag for this container image in the registry
- update our daily run to utilize the tags that are available in the registry

**Comment by sarcasticadmin** [comment]
> Our daily run is broken.

Good catch! Looks like it goes back a few weeks https://github.com/Nebulaworks/nix-garage/actions/runs/1462892845 I suspect somethings changed off `master` around the functions we are leveraging. Totally expected though and more or less the point of doing this daily build :slightly_smiling_face: 

> produce a latest tag for this container image in the registry

The `latest` tag isnt honored (https://github.com/Nebulaworks/nix-garage/blob/master/imgs/awsutils/default.nix#L10-L12) a bit misleading but its is more of a dummy value. The `latest` tag is overridden by the drv hash which is the `tag` we use in dockerhub: https://github.com/Nebulaworks/nix-garage/blob/master/publish-imgs#L64-L74

Looks like well be syncing up later today so Ill talk to you about it more then
