### ISSUE TITLE
daily builds appear to be broken

### ISSUE THREAD

**Issue by ruebenramirez** [Nebulaworks/nix-garage#47]
daily build workflow breakage:
https://github.com/Nebulaworks/nix-garage/runs/4913402701?check_suite_focus=true#step:4:707

The build appears to be looking for a dependency at `https://github.com/tfsec/tfsec` that has since been moved to `https://github.com/aquasecurity/tfsec`.  (If you visit the first url in your browser, it redirects you to the 2nd url.)

**Comment by ruebenramirez** [comment]
The sha we're referencing here has references to the old repo: https://github.com/aquasecurity/tfsec/blob/17acbbd9e5628f6ccbe694fc5f368720fb3e4666/cmd/tfsec/main.go#L10

In later updates to the repo, these references have been patched up: https://github.com/aquasecurity/tfsec/blob/v0.63.1/cmd/tfsec/main.go

**Comment by ruebenramirez** [comment]
I see that we can't simply update to the latest release of tfsec without feeling some pain in the processes that use the older tfsec release.  @davido-nw has a comment that we need to remmediate tfsec run output delta that results from upgrading the tfsec release we depend on: https://github.com/Nebulaworks/nix-garage/blob/master/imgs/nwi-pr-utils/default.nix#L7

I'll go ahead and put in the PR to upgrade the tfsec. This way it's ready to go, after we remediate our downstream processes that utilize the older tfsec release.

**Comment by ruebenramirez** [comment]
As an ugly temp fix, we could fork the 0.39.26 code, update the go dependency references to utilize the updated `github.com/aquasecurity/tfsec` repo url.  

I would consider this a temporary fix only if we prioritize accounting for the delta in the downstream CI that currently depends on the older v0.39.26 tfsec release.

**Comment by sarcasticadmin** [comment]
@ruebenramirez thank for jump on this!

**Comment by sarcasticadmin** [comment]
Ok now that Im caught up:

It looks like since the go code is referencing the old paths `github.com/tfsec/tfsec`, which do redirect to the new namespace `github.com/aquasecurity/tfsec` lovely :facepalm: I just hope this wasnt a marketing mandate that let to this migration of the repo to the parent org.

I would say the fix is probably much simpler: we can start building with latest tfsec in nixpkgs upstream since we were planning to remove our need for such an old version very soon. But your call out to temporary fix the 0.39.x release is also totally something that would have been reasonable if we needed to say on that version.

**Comment by davido-nw** [comment]
I already have an issue to upgrade tfsec partially for that reason. I can
try to split time on that issue next week.

I also haven't been receiving emails about the upstream failing the daily
runs so this is kinda news to me.

**Comment by sarcasticadmin** [comment]
> I also haven't been receiving emails about the upstream failing the daily
runs so this is kinda news to me.

I think it depends on your `watch` settings globally and per repos. But either way its not like its immediately effecting running systems, and thats why were doing these daily anyway :slightly_smiling_face:

**Comment by davido-nw** [comment]
Looks like handling the image was already done. Specifically, I want to
actually use the new tfsec against env/infra and remediate or ignore as
necessary. That's the non-trivial part.
