### ISSUE TITLE
Investigate shellhook and makeWrapper for helmsman-aws image

### ISSUE THREAD

**Issue by Lynty** [Nebulaworks/nix-garage#5]
We need a way to export the environment variable `HELM_PLUGINS` from the `helm-diff` derivation. The current workaround is setting it in the Nebulaworks docker image.

Investigate using `shellhook` or `makeWrapper` to set the environment variable and make it available to the nix profile.

**Comment by sarcasticadmin** [comment]
`helm-diff` was added to upstream nixpkgs: https://github.com/NixOS/nixpkgs/pull/106901

Going to close this now, since its no longer needed.
